CREATE TABLE IF NOT EXISTS categorias (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre TEXT NOT NULL UNIQUE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS productos (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre TEXT NOT NULL,
  descripcion TEXT,
  precio NUMERIC(12,2) NOT NULL DEFAULT 0,
  categoria TEXT,
  categoria_id BIGINT REFERENCES categorias(id),
  url_imagen TEXT,
  disponible BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Migración para instalaciones creadas con una versión anterior del esquema.
-- CREATE TABLE IF NOT EXISTS no agrega columnas a tablas ya existentes.
ALTER TABLE productos ADD COLUMN IF NOT EXISTS categoria TEXT;
ALTER TABLE productos ADD COLUMN IF NOT EXISTS stock INTEGER NOT NULL DEFAULT 0;

CREATE INDEX IF NOT EXISTS idx_productos_categoria ON productos(categoria);
CREATE INDEX IF NOT EXISTS idx_productos_disponible ON productos(disponible);
CREATE INDEX IF NOT EXISTS idx_productos_stock ON productos(stock);

-- Modelo del Dashboard: registra cada entrada o salida de inventario.
CREATE TABLE IF NOT EXISTS dashboard (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  producto_id BIGINT NOT NULL REFERENCES productos(id) ON DELETE CASCADE,
  tipo_movimiento TEXT NOT NULL CHECK (tipo_movimiento IN ('entrada', 'salida')),
  cantidad INTEGER NOT NULL CHECK (cantidad > 0),
  fecha_movimiento TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  notas TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_dashboard_producto ON dashboard(producto_id);
CREATE INDEX IF NOT EXISTS idx_dashboard_tipo ON dashboard(tipo_movimiento);
CREATE INDEX IF NOT EXISTS idx_dashboard_fecha ON dashboard(fecha_movimiento DESC);

-- Resumen que usa el Dashboard para ordenar los productos por entradas.
DROP VIEW IF EXISTS dashboard_productos;
CREATE OR REPLACE VIEW dashboard_productos AS
SELECT
  p.id,
  p.nombre,
  p.categoria,
  p.precio,
  p.url_imagen,
  p.disponible,
  COALESCE(SUM(d.cantidad) FILTER (WHERE d.tipo_movimiento = 'entrada'), 0) AS total_ingresos,
  COALESCE(SUM(d.cantidad) FILTER (WHERE d.tipo_movimiento = 'salida'), 0) AS total_salidas,
  MAX(d.fecha_movimiento) FILTER (WHERE d.tipo_movimiento = 'entrada') AS ultimo_ingreso,
  p.created_at
FROM productos p
LEFT JOIN dashboard d ON d.producto_id = p.id
GROUP BY p.id, p.nombre, p.categoria, p.precio, p.url_imagen, p.disponible, p.created_at
ORDER BY total_ingresos DESC, p.created_at DESC;

ALTER TABLE categorias ENABLE ROW LEVEL SECURITY;
ALTER TABLE productos ENABLE ROW LEVEL SECURITY;
ALTER TABLE dashboard ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "categorias_all_access" ON categorias;
CREATE POLICY "categorias_all_access" ON categorias
FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "productos_all_access" ON productos;
CREATE POLICY "productos_all_access" ON productos
FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "dashboard_all_access" ON dashboard;
CREATE POLICY "dashboard_all_access" ON dashboard
FOR ALL USING (true) WITH CHECK (true);

-- Storage para las imágenes del catálogo.
-- Ejecuta este bloque con el SQL Editor de Supabase; la clave anon no puede crear buckets.
INSERT INTO storage.buckets (id, name, public)
VALUES ('fotos-catalogo', 'fotos-catalogo', TRUE)
ON CONFLICT (id) DO UPDATE SET public = TRUE;

DROP POLICY IF EXISTS "fotos_catalogo_public_read" ON storage.objects;
CREATE POLICY "fotos_catalogo_public_read" ON storage.objects
FOR SELECT USING (bucket_id = 'fotos-catalogo');

DROP POLICY IF EXISTS "fotos_catalogo_authenticated_insert" ON storage.objects;
CREATE POLICY "fotos_catalogo_authenticated_insert" ON storage.objects
FOR INSERT TO authenticated
WITH CHECK (bucket_id = 'fotos-catalogo');

DROP POLICY IF EXISTS "fotos_catalogo_authenticated_update" ON storage.objects;
CREATE POLICY "fotos_catalogo_authenticated_update" ON storage.objects
FOR UPDATE TO authenticated
USING (bucket_id = 'fotos-catalogo')
WITH CHECK (bucket_id = 'fotos-catalogo');

DROP POLICY IF EXISTS "fotos_catalogo_authenticated_delete" ON storage.objects;
CREATE POLICY "fotos_catalogo_authenticated_delete" ON storage.objects
FOR DELETE TO authenticated
USING (bucket_id = 'fotos-catalogo');

-- Opcional: ejemplo de inserción
-- INSERT INTO categorias (nombre) VALUES ('Ropa');
-- INSERT INTO productos (nombre, descripcion, precio, categoria, url_imagen, disponible)
-- VALUES ('Camisa', 'Descripción', 45000, 'Ropa', 'https://lh3.googleusercontent.com/d/ID_DE_IMAGEN', true);
-- INSERT INTO dashboard (producto_id, tipo_movimiento, cantidad, notas)
-- VALUES (1, 'entrada', 10, 'Ingreso inicial');

-- Actualiza PostgREST después de aplicar migraciones en el SQL Editor.
NOTIFY pgrst, 'reload schema';
