CREATE TABLE IF NOT EXISTS categorias (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre TEXT NOT NULL UNIQUE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS productos (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre TEXT NOT NULL,
  descripcion TEXT,
  precio NUMERIC(12,2) NOT NULL DEFAULT 0,
  categoria TEXT,
  categoria_id BIGINT REFERENCES categorias(id),
  url_imagen TEXT,
  disponible BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_productos_categoria ON productos(categoria);
CREATE INDEX IF NOT EXISTS idx_productos_disponible ON productos(disponible);

ALTER TABLE categorias ENABLE ROW LEVEL SECURITY;
ALTER TABLE productos ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "categorias_all_access" ON categorias;
CREATE POLICY "categorias_all_access" ON categorias
FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "productos_all_access" ON productos;
CREATE POLICY "productos_all_access" ON productos
FOR ALL USING (true) WITH CHECK (true);

-- Opcional: ejemplo de inserción
-- INSERT INTO categorias (nombre) VALUES ('Ropa');
-- INSERT INTO productos (nombre, descripcion, precio, categoria, url_imagen, disponible)
-- VALUES ('Camisa', 'Descripción', 45000, 'Ropa', 'https://lh3.googleusercontent.com/d/ID_DE_IMAGEN', true);
